@extends('layouts.app')
@section('title', 'Select Analysis Type')
@section('page-title', 'Select Analysis Type')
@section('content')

<div class="row mb-3">
    <div class="col-md-8">
        <h2><i class="fas fa-vial me-2"></i>{{ $sample->sample_name }}</h2>
        <p class="text-muted mb-0">
            <strong>{{ $sample->farm->farm_name }}</strong> — {{ $sample->farm->farmer->full_name }}
            &middot; Received {{ $sample->sample_date->format('M j, Y') }}
        </p>
    </div>
    <div class="col-md-4 text-end">
        <a href="{{ route('farms.show', $sample->farm) }}" class="btn btn-outline-secondary"><i class="fas fa-arrow-left me-1"></i>Back to Farm</a>
    </div>
</div>

<div class="row g-3 align-items-start">
    <!-- Manual Entry Card -->
    <div class="col-md-4">
        <div class="card h-100">
            <div class="card-body text-center d-flex flex-column" style="min-height: 220px;">
                <i class="fas fa-keyboard fa-3x text-success mb-3"></i>
                <h5>Manual Entry</h5>
                <p class="text-muted small flex-grow-1">Enter laboratory values directly, or select the observed reagent color for pH and N/P/K — same calibration engine as colorimetric analysis.</p>
                <a href="{{ route('analyses.create.manual', $sample) }}" class="btn btn-success mt-auto">Start Manual Entry</a>
            </div>
        </div>
    </div>

    <!-- Colorimetric Analysis Card -->
    <div class="col-md-4">
        <div class="card h-100">
            <div class="card-body text-center d-flex flex-column" style="min-height: 220px;">
                <i class="fas fa-camera fa-3x text-success mb-3"></i>
                <h5>Colorimetric Analysis</h5>
                <p class="text-muted small flex-grow-1">Capture soil color via webcam and let the color-analysis engine compute NPK and pH.</p>
                <form method="POST" action="{{ route('analyses.start.colorimetric', $sample) }}" class="mt-auto">
                    @csrf
                    <button type="submit" class="btn btn-success w-100">Start Colorimetric Analysis</button>
                </form>
            </div>
        </div>
    </div>

    <!-- Digital Probe Card -->
    <div class="col-md-4">
        <div class="card h-100">
            <div class="card-body text-center d-flex flex-column" style="min-height: 220px;">
                <i class="fas fa-qrcode fa-3x text-success mb-3"></i>
                <h5>Digital Probe</h5>
                <p class="text-muted small flex-grow-1">Scan the QR code generated by the Arduino soil probe to auto-populate readings.</p>
                <a href="{{ route('analyses.create.probe', $sample) }}" class="btn btn-success mt-auto">Scan Probe QR Code</a>
            </div>
        </div>
    </div>
</div>
@endsection
