@extends('layouts.app')
@section('title', 'Create Analysis')
@section('content')

<div class="row mb-3">
    <div class="col-md-8">
        <h2><i class="fas fa-vial me-2"></i>Create Soil Analysis</h2>
        <p class="text-muted mb-0">For <strong>{{ $farm->farm_name }}</strong> — {{ $farm->farmer->full_name }}</p>
    </div>
    <div class="col-md-4 text-end">
        <a href="{{ route('farms.show', $farm) }}" class="btn btn-outline-secondary"><i class="fas fa-arrow-left me-1"></i>Back to Farm</a>
    </div>
</div>

<div class="row g-3">
    <div class="col-md-4">
        <div class="card h-100">
            <div class="card-body text-center d-flex flex-column">
                <i class="fas fa-keyboard fa-3x text-success mb-3"></i>
                <h5>Manual Entry</h5>
                <p class="text-muted small flex-grow-1">Enter laboratory or field-measured pH/N/P/K values directly.</p>
                <a href="{{ route('analyses.create.manual', $farm) }}" class="btn btn-success">Start Manual Entry</a>
            </div>
        </div>
    </div>
    <div class="col-md-4">
        <div class="card h-100">
            <div class="card-body text-center d-flex flex-column">
                <i class="fas fa-camera fa-3x text-success mb-3"></i>
                <h5>Colorimetric Analysis</h5>
                <p class="text-muted small flex-grow-1">Capture soil color via webcam and let the color-analysis engine compute NPK and pH.</p>
                <button type="button" class="btn btn-success" data-bs-toggle="collapse" data-bs-target="#colorimetricForm">
                    Start Colorimetric Analysis
                </button>
            </div>
        </div>
        <div class="collapse mt-2" id="colorimetricForm">
            <div class="card card-body">
                <form method="POST" action="{{ route('analyses.store', $farm) }}">
                    @csrf
                    <input type="hidden" name="analysis_type" value="colorimetric">
                    <div class="mb-2">
                        <label class="form-label small">Sample Name</label>
                        <input type="text" name="sample_name" class="form-control form-control-sm" required>
                    </div>
                    <div class="mb-2">
                        <label class="form-label small">Sample Date</label>
                        <input type="date" name="sample_date" class="form-control form-control-sm" value="{{ date('Y-m-d') }}" required>
                    </div>
                    <div class="mb-2">
                        <label class="form-label small">Date Tested</label>
                        <input type="date" name="date_tested" class="form-control form-control-sm" value="{{ date('Y-m-d') }}" required>
                    </div>
                    <button type="submit" class="btn btn-sm btn-success w-100">Continue to Capture</button>
                </form>
            </div>
        </div>
    </div>
    <div class="col-md-4">
        <div class="card h-100">
            <div class="card-body text-center d-flex flex-column">
                <i class="fas fa-qrcode fa-3x text-success mb-3"></i>
                <h5>Digital Probe</h5>
                <p class="text-muted small flex-grow-1">Scan the QR code generated by the Arduino soil probe to auto-populate readings.</p>
                <a href="{{ route('analyses.create.probe', $farm) }}" class="btn btn-success">Scan Probe QR Code</a>
            </div>
        </div>
    </div>
</div>
@endsection
